version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_user
      MONGO_INITDB_ROOT_PASSWORD: dev_password
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet mongodb:27017/mydatabase --username admin --password secret",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: player_exercise
    restart: always
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    environment:
      STAGE: dev
      DB_HOST: mongodb
      DB_USER: dev_user
      DB_PASSWORD: dev_password
